[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[build-dependencies]
config = { path = "../config" }

[dependencies]
config = { path = "../config" }

bootloader_api = "0.11.12"
acpi = "4.1.1"
spin = "0.10.0"
volatile = "0.3.0"
x86_64 = "0.15.2"
goblin = { version = "0.10.0", default-features = false, features = ["elf32", "elf64", "endian_fd"] }
uart_16550 = "0.3.2"
pic8259 = "0.11.0"
pc-keyboard = "0.8.0"
linked_list_allocator = "0.10.5"
crossbeam-queue = { version = "0.3.12", default-features = false, features = ["alloc"] }
lazy_static = { version = "1.5", features = ["spin_no_std"] }
conquer-once = { version = "0.4.0", default-features = false }
futures-util = { version = "0.3.31", default-features = false, features = ["alloc"] }
spinning_top = "0.3.0"
hashbrown = "0.15.4"
ps2-mouse = "0.1.4"
raw-cpuid = "11.5.0"

[dependencies.noto-sans-mono-bitmap]
version = "0.3"
default-features = false
features = [
    "font_weights_all",
    "raster_heights_all",
    "unicode-basic-latin",
    # required for the fallback char 'ï¿½'
    "unicode-specials",
]
