theme: just-the-docs
title: Goofy OS Documentation
author: RetrogradeDev
description: Comprehensive documentation for Goofy OS, a hobbyist operating system project.
color_scheme: dark
url: https://retrogradedev.github.io/goofy-os
